### ISSUE TITLE
Determine the language of a new feed

### ISSUE THREAD

**Issue by jbionic2016** [gromnitsky/grepfeed#4]
Hi there, Thanks for your marvellous RSS filter service

I just thought it would be wonderfull if it could also analyse and determine the language of a new feed
take for instance the following RSS: https://libgen.st/rss/index.php
some ebooks are in English, some in German, some in Polish. So if a subscriber can't read in all those languages, then perhaps it is better to filter some feeds out

**Comment by gromnitsky** [comment]
the provided feed already contains enough metadata to do that. here is how to filter-out all non-English books:

https://grepfeed.sigwait.tk/?url=https%3A%2F%2Flibgen.st%2Frss%2Findex.php&filter=Language%3A+English

or to get only English and Czech:

https://grepfeed.sigwait.tk/?url=https%3A%2F%2Flibgen.st%2Frss%2Findex.php&filter=%27Language%3A+%28Czech%7CEnglish%29%27

**Comment by gromnitsky** [comment]
побачив що відповідаю русні :(

нахуй шуруй звідси, підар
